### PR TITLE
Yahoo Japan MX. And a few clarifications about Zoho to comment on.

### PR DESCRIPTION
**Pull request by miteshashar**

### CODE REVIEW

**Comment by miteshashar** [comment]
Noticed this yesterday for zoho paid & free personal offerings. Please comment on how it should be ideally included. Also, mx3 is common for both the services.
`'zoho-mail': {'mx': [
    'mx.zoho.com',
    'mx2.zoho.com',
    ]},
'zoho-personal': {'mx': [
    'smtpin.zoho.com',
    'smtpin2.zoho.com',
    'mx3.zoho.com',
    ]},`

**Comment by miteshashar** [comment]
@jace If there is a differentiation between regular email & custom-domain email for Google, shouldn't it also be present for others like Yahoo, Zoho, etc?
That differentiation could be useful quantifiable data in some cases.

**Comment by jace** [comment]
Let's split Zoho. For Yahoo, I found lots of MX servers and no clear way to differentiate.

**Comment by jace** [comment]
@miteshashar Anything new on Zoho? I've added a `public` flag to the provider list to indicate a public email service provider, and specifically thanks to Zoho, added a separate list of domains. This will now deprecate the `webmail_domains` list in Baseframe.

**Comment by miteshashar** [comment]
Hi @jace!
I did some `dig`ging.
#### MX for zoho.com (Personal)
```
zoho.com.		300	IN	MX	20 smtpin2.zoho.com.
zoho.com.		300	IN	MX	10 smtpin.zoho.com.
zoho.com.		300	IN	MX	50 mx3.zoho.com.
```
#### MX for zohomail.com (I presume it is for Zoho Workplace – New name for their paid service)
```
zohomail.com.		300	IN	MX	10 mx2.zohocorp.com.
zohomail.com.		300	IN	MX	50 mx3.zohomail.com.
zohomail.com.		300	IN	MX	20 mx.zohocorp.com.
```
I tried to figure out a few domains that use Zoho Workplace.
#### Domain 1
```
shoutdreams.com.	300	IN	MX	20 mx.zohomail.com.
shoutdreams.com.	300	IN	MX	10 mx.zohomail.com.
```
#### Domain 2
```
rideoncab.com.		1800	IN	MX	20 mx2.zoho.com.
rideoncab.com.		1800	IN	MX	10 mx.zoho.com.
```
#### Domain 3
```
twoblacknerds.com.	60	IN	MX	20 mx2.zoho.com.
twoblacknerds.com.	60	IN	MX	10 mx.zoho.com.
```

Evidently, only `zoho.com` is public & remaining are paid. I have an element of doubt for `zohomail.com` though.

Given the differences in MX records of Zoho Workplace domains, for Zoho the best way to determine whether the service is public or paid, is to validate the domain for `From`.

**Comment by jace** [comment]
So the current solution of whitelisting `zoho.com` specifically as a public domain is the way to go then.

**Pull request merged**
